PREFIX fairo: <https://w3id.org/fair-o#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?assessment ?subPrinciple ?subPrincipleLabel ?value ?outcome ?outcomeLabel
WHERE {
  ?assessment a fairo:FAIRAssessment ;
              fairo:hasSubPrincipleResult ?result .

  ?result fairo:forSubPrinciple ?subPrinciple ;
          fairo:value ?value ;
          fairo:testResult ?outcome .

  OPTIONAL {
    ?subPrinciple rdfs:label ?subPrincipleLabel .
  }

  OPTIONAL {
    ?outcome rdfs:label ?outcomeLabel .
  }
}
ORDER BY ?assessment ?subPrinciple