PREFIX fairo: <https://w3id.org/fair-o#>

SELECT ?assessment ?subPrinciple ?result ?value ?outcome ?evidence
WHERE {
  ?assessment a fairo:FAIRAssessment ;
              fairo:hasSubPrincipleResult ?result .

  ?result fairo:forSubPrinciple ?subPrinciple .

  OPTIONAL {
    ?result fairo:value ?value .
  }

  OPTIONAL {
    ?result fairo:testResult ?outcome .
  }

  OPTIONAL {
    ?result fairo:evidence ?evidence .
  }
}
ORDER BY ?assessment ?subPrinciple