PREFIX fairo: <https://w3id.org/fair-o#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?algorithm ?algorithmLabel ?scoringFunction ?scoringFunctionLabel ?formula ?minValue ?maxValue
WHERE {
  ?algorithm a fairo:CalculationAlgorithm ;
             fairo:appliesScoringFunction ?scoringFunction .

  OPTIONAL {
    ?algorithm rdfs:label ?algorithmLabel .
  }

  OPTIONAL {
    ?scoringFunction rdfs:label ?scoringFunctionLabel .
  }

  OPTIONAL {
    ?scoringFunction fairo:formula ?formula .
  }

  OPTIONAL {
    ?scoringFunction fairo:minValue ?minValue .
  }

  OPTIONAL {
    ?scoringFunction fairo:maxValue ?maxValue .
  }
}
ORDER BY ?algorithm