PREFIX fairo: <https://w3id.org/fair-o#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?assessment ?subPrinciple ?result ?algorithm ?softwareAgent ?softwareAgentLabel
WHERE {
  ?assessment a fairo:FAIRAssessment ;
              fairo:hasSubPrincipleResult ?result .

  ?result fairo:forSubPrinciple ?subPrinciple ;
          fairo:computedUsing ?algorithm .

  ?algorithm fairo:implementedBy ?softwareAgent .

  ?softwareAgent a prov:SoftwareAgent .

  OPTIONAL {
    ?softwareAgent rdfs:label ?softwareAgentLabel .
  }
}
ORDER BY ?assessment ?subPrinciple